(function(){
    'use strict';

    /**
     * This is a sample service
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Tapas Jena
     * @copyright: Anitech Consulting Services Pvt Ltd.
     */
    angular.module('home').service('homeService', function($http, $q) {

        var adList = '';

        this.getAds = function(){
            var deferred = $q.defer();

            $http.post('../data/ws/ads/search').success(function (data) {
                adList = data.responseObj;
                deferred.resolve(adList);
            });
            return deferred.promise;
        };

    });

})();
